### ISSUE TITLE
Script fails with 'Patch Missing' error after successfully downloading patches

### ISSUE THREAD

**Issue by sinksc** [ojehle/H35_OraclePatchDownloader#1]
RedHat Linux 8
Whenever running the script to download patches, it downloads the patches successfully, but then says 'Patch <patchnumber> missing', and exits with a return code of 1. I have tried this with several different patches and the result is the same:

```
$java -jar oraclePatchDownloader-1.0.0.jar -u $MOSUser -p $MOSPassword -x 36057774 -t 226P -d $downloadDir
File PEOPLETOOLS-LNX-8.60.11_1of4.zip downloaded successfully.
File PEOPLETOOLS-LNX-8.60.11_2of4.zip downloaded successfully.
File PEOPLETOOLS-LNX-8.60.11_3of4.zip downloaded successfully.
File PEOPLETOOLS-LNX-8.60.11_4of4.zip downloaded successfully.
Patch 36057774 missing
```

**Comment by ojehle** [comment]
> RedHat Linux 8 Whenever running the script to download patches, it downloads the patches successfully, but then says 'Patch missing', and exits with a return code of 1. I have tried this with several different patches and the result is the same:
> 
> ```
> $java -jar oraclePatchDownloader-1.0.0.jar -u $MOSUser -p $MOSPassword -x 36057774 -t 226P -d $downloadDir
> File PEOPLETOOLS-LNX-8.60.11_1of4.zip downloaded successfully.
> File PEOPLETOOLS-LNX-8.60.11_2of4.zip downloaded successfully.
> File PEOPLETOOLS-LNX-8.60.11_3of4.zip downloaded successfully.
> File PEOPLETOOLS-LNX-8.60.11_4of4.zip downloaded successfully.
> Patch 36057774 missing
> ```

I expect because the number of the file is not in the zip file name...   could fix that

**Comment by ojehle** [comment]
can you try with the latest version ?? i added the -c --check option and disabled by default the checking.

as i work mostly with databases, the patches are in form 

p99999999.zip.... so we i can check if the patch is downloaded.  but this will done only if -c or --check is passed

thanks for testing and closing this ticket when the test was successfull

**Comment by sinksc** [comment]
Yes, that worked great. Thanks for the quick fix! I think it would be helpful to note in the readme that using `-c` assumes that the patch files are named `pxxxxxxxx.zip`.

Closing Issue. Thanks again.
