### ISSUE TITLE
Occasionally receive "Patch XXXXX missing", exit code 1

### ISSUE THREAD

**Issue by rjmitche77** [ojehle/H35_OraclePatchDownloader#2]
For some patches the downloader will report "Patch xxxxx missing" however it seems to download all the requisite files fine. For example, PATCHID 35911235 Platform: Linux x86_64, there are 4 files. These download fine but the downloader reports "Patch 35911235 missing" and exits with status 1.

$ java -jar oraclePatchDownloader-1.0.0.jar -x 35911235 -t 226P -u xxxxx -p yyyy

File PEOPLETOOLS-LNX-8.59.22_1of4.zip downloaded successfully.
File PEOPLETOOLS-LNX-8.59.22_2of4.zip downloaded successfully.
File PEOPLETOOLS-LNX-8.59.22_3of4.zip downloaded successfully.
File PEOPLETOOLS-LNX-8.59.22_4of4.zip downloaded successfully.
Patch 35911235 missing

**Comment by ojehle** [comment]
already closed with ticket #1 .. check out the latest sources
