### ISSUE TITLE
Possibility to download language translated patch

### ISSUE THREAD

**Issue by sibylmarziopulcini** [ojehle/H35_OraclePatchDownloader#3]
I would like to use the tool to download language translated patch (e.g. E-Business Suite patches). For example, I could download patch
35697293  with the following command:

java -jar oraclePatchDownloader-1.0.1.jar -u xxx@xxx.com -p <pwd> -x 35697293 -t 226P -d .

but language translated patch require a "platform" value like for example 108L;Italian (I), 2L;French (F) as in the "old" getMOSPatch.

Would it be possible to add this feature?
Regards,
Marzio

**Comment by ojehle** [comment]
> I would like to use the tool to download language translated patch (e.g. E-Business Suite patches). For example, I could download patch 35697293 with the following command:
> 
> java -jar oraclePatchDownloader-1.0.1.jar -u [xxx@xxx.com](mailto:xxx@xxx.com) -p -x 35697293 -t 226P -d .
> 
> but language translated patch require a "platform" value like for example 108L;Italian (I), 2L;French (F) as in the "old" getMOSPatch.
> 
> Would it be possible to add this feature? Regards, Marzio

i will look on it .... should not be a big issue, but i never worked with the language translated patches of oracle.

**Comment by ojehle** [comment]
the fixed version 1.0.2 is now in the git, works for me .
you can select a list of -t --plattforms now, comma separated.. for your example

java -jar oraclePatchDownloader-1.0.2.jar -u [xxx@xxx.com](mailto:xxx@xxx.com) -p -x 35697293 -t 226P,4L,2L -d .

can you please try and close afterwords if its ok?

**Comment by sibylmarziopulcini** [comment]
Hi, and sorry for the delay in my answer. I could test the new version only today and It works fine for me using comma separated platform codes. Thank you for adding this feature!
