### ISSUE TITLE
Probably provide downloadable releases?

### ISSUE THREAD

**Issue by farblos** [ojehle/H35_OraclePatchDownloader#8]
Me again ... I thought that some users might like to have downloadable releases.  Since you already have that nice maven build process with its self-contained jar as output, extending the GitHub action to upload the resulting jar wasn't that difficult.

You could check the new yaml file [here](https://github.com/farblos/H35_OraclePatchDownloader/blob/add-release-process/.github/workflows/build-and-release.yml).  It works exactly as before, plus creates a release when triggered appropriately.

And a resulting test release is [here](https://github.com/farblos/H35_OraclePatchDownloader/releases).

To trigger a new release, you have to push an annotated (`-a`) tag named `vX.Y.Z` to GitHub.  The tag description (without its subject in the first line) is taken as release description.

Only it is you who has to maintain that stuff in the long-term and care about the releases, so I'd like to hear your opinion first before I brush up that PR...

**Comment by ojehle** [comment]
one thing on my todo list :-)  Please brush up the PR.

**Comment by farblos** [comment]
OK, and thanks for the collaboration invitation.

Which I have used to merge my own PR #9 into your master.

Probably you could give the release process a try?  (I even have added a short description in pom.xml.)  Using the current version 1.0.4 should be just fine, I think.
